openapi: 3.0.0
info:
  title: Bewerbungsmanager API
  version: '1.0.0'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/user/register:
    post:
      summary: Register a new user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input

  /api/user/login:
    post:
      summary: Login a user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Invalid credentials

  /api/user/account:
    get:
      summary: Get user profile
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile data
        '401':
          description: Unauthorized

    patch:
      summary: Update user name
      tags:
        - User
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: Name updated
        '401':
          description: Unauthorized

    delete:
      summary: Delete user profile
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User deleted
        '401':
          description: Unauthorized

  /api/user/account/password:
    patch:
      summary: Change user password
      tags:
        - User
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: Password changed
        '401':
          description: Unauthorized
        '400':
          description: Invalid input
