openapi: 3.0.0
info:
  title: Bewerbungsmanager API
  version: '1.0.0'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/applications/{applicationId}/notes:
    parameters:
      - in: path
        name: applicationId
        required: true
        schema:
          type: integer
          format: int32
          minimum: 1

    get:
      summary: Listet alle Notizen der eigenen Bewerbung auf
      tags: [Notes]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Liste von Notizen
        '400':
          description: Bad Request
        '401':
          description: Unauthorized

    post:
      summary: Legt eine neue Notiz an (nur für eigene Bewerbung)
      tags: [Notes]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                date:
                  type: string
                  format: date-time
                  nullable: true
                text:
                  type: string
            example:
              date: '2025-08-14T16:03:28.358Z'
              text: 'string'
      responses:
        '201':
          description: Angelegte Notiz
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Application not found or not owned by user

  /api/applications/{applicationId}/notes/{noteId}:
    parameters:
      - in: path
        name: applicationId
        required: true
        schema:
          type: integer
          format: int32
          minimum: 1
      - in: path
        name: noteId
        required: true
        schema:
          type: integer
          format: int32
          minimum: 1

    patch:
      summary: Aktualisiert eine Notiz (nur für eigene Bewerbung)
      tags: [Notes]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date-time
                  nullable: true
                text:
                  type: string
              minProperties: 1
      responses:
        '200':
          description: Aktualisierte Notiz
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Note not found / not owned or nothing to update

    delete:
      summary: Löscht eine Notiz (nur für eigene Bewerbung)
      tags: [Notes]
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Gelöscht
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Note not found or not owned by user
